# config/packages/kreyu_data_table.yaml
kreyu_data_table:
  defaults:
    personalization:
      enabled: true
    pagination:
      enabled: true
    exporting:
      enabled: true
    sorting:
      enabled: true
    filtration:
      enabled: true
    themes:
      - '@KreyuDataTable/themes/bootstrap_5.html.twig'